spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meta_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
#    show-sql: true      # SQL 쿼리 로깅 (개발 중에만 true)
#    properties:
#      hibernate:
#        format_sql: true
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
  jooq:
    sql-dialect: POSTGRES

  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/meta_db?authSource=admin
      database: meta_db
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  messaging:
    stomp:
      broker-relay:
        host: localhost  # RabbitMQ 서버 IP
        port: 61613           # STOMP 기본 포트
        system-login: admin   # RabbitMQ 로그인 계정
        system-passcode: admin
        relay-host: localhost
        relay-port: 61613
        client-login: admin
        client-passcode: admin

# Swagger 설정 추가
springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    config-url: /v1/api-docs/swagger-config
    url: /v1/api-docs
    groups-order: DESC
    operations-sorter: method
    tags-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

#logging:
#  level:
#    org.springframework.web: DEBUG
#    team.klover: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE
#    org.jooq.tools.LoggerListener: DEBUG

es:
  host: "localhost"