spring:
  datasource:
    url: jdbc:postgresql://175.45.192.38:5432/meta_db
    username: postgres
    password: hsol9789!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false      # 운영 환경에서는 보통 false로 설정
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: my-redis
      port: 6379
    mongodb:
      uri: mongodb://admin:admin@175.45.192.38:27017/meta_db?authSource=admin
      database: meta_db
  rabbitmq:
    host: 13.125.47.222
    port: 5672
    username: admin
    password: admin
  messaging:
    stomp:
      broker-relay:
        host: 13.125.47.222  # RabbitMQ 서버 IP
        port: 61613           # STOMP 기본 포트
        system-login: admin   # RabbitMQ 로그인 계정
        system-passcode: admin
        relay-host: 13.125.47.222
        relay-port: 61613
        client-login: admin
        client-passcode: admin

# Swagger 비활성화 (운영 환경에서는 보통 사용 안 함)
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    team.klover: DEBUG  # 내 애플리케이션 패키지는 DEBUG 유지 가능
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/app.log
  logback:
    rolling policy:
      file-name-pattern: logs/app-%d{yyyy-MM-dd}.log
      max-history: 7
      total-size-cap: 100MB
es:
  host: "es.tmdgjsdl1.site"
