input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql-42.3.1.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://host.docker.internal:5432/meta_db"
    jdbc_user => "postgres"
    jdbc_password => "postgres"
    statement => "select cp.id,cp.member_id,cp.content,cp.create_date,cp.modify_date,cp.mapX,cp.mapY,cp.language, cp.image_urls::text, COALESCE(COUNT(DISTINCT l.id),0) AS like_count, COALESCE(COUNT(DISTINCT c.id), 0) AS comment_count, m.nickname FROM comm_post cp LEFT JOIN comm_post_like l ON cp.id = l.comm_post_id LEFT JOIN comment c ON cp.id = c.comm_post_id left join members m on cp.member_id = m.id WHERE cp.id > :sql_last_value GROUP BY cp.id,m.id ORDER BY cp.id ASC"
    schedule => "*/2 * * * *"
    sql_log_level => "debug"
    tracking_column => "id"
    use_column_value => true
    record_last_run => true
    last_run_metadata_path => "/usr/share/logstash/commpost_last_run_metadata"
  }
}
filter {
  mutate {
    convert => {"%{mapy}" => "float"}
    convert => {"%{mapx}" => "float"}
  }
  mutate {
    add_field => { "[location][lat]" => "%{mapy}" }
    add_field => { "[location][lon]" => "%{mapx}" }
  }
  mutate {
    remove_field => ["@version", "jdbc_connection_string", "jdbc_user", "jdbc_password", "mapx", "mapy"]
  }
  mutate {
    convert => {"[location][lat]" => "float"}
    convert => {"[location][lon]" => "float"}
  }
    ruby {
      code => "
        event.set('[location]', { 'lat' => event.get('[location][lat]'), 'lon' => event.get('[location][lon]') })
      "
    }
}
output {
  if [language] == "KO"{
      elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "commpostkor"
        document_id => "%{id}"
        manage_template => true
        template_name => "commpostkortemplate"
        template => "/usr/share/logstash/template/CommPostKoreanTemplate.json"
        template_overwrite => true
      }
  }
    if [language] == "JA"{
        elasticsearch {
          hosts => ["elasticsearch:9200"]
          index => "commpostjpn"
          document_id => "%{id}"
          manage_template => true
          template_name => "commpostjpntemplate"
          template => "/usr/share/logstash/template/CommPostJapaneseTemplate.json"
          template_overwrite => true
        }
   }
    if [language] == "ZH"{
        elasticsearch {
          hosts => ["elasticsearch:9200"]
          index => "commpostchs"
          document_id => "%{id}"
          manage_template => true
          template_name => "commpostchstemplate"
          template => "/usr/share/logstash/template/CommPostChineseTemplate.json"
          template_overwrite => true
        }
    }
      if [language] == "EN"{
          elasticsearch {
            hosts => ["elasticsearch:9200"]
            index => "commposteng"
            document_id => "%{id}"
            manage_template => true
            template_name => "commpostengtemplate"
            template => "/usr/share/logstash/template/CommPostEnglishTemplate.json"
            template_overwrite => true
          }
      }
}