input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql-42.3.1.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://host.docker.internal:5432/meta_db"
    jdbc_user => "postgres"
    jdbc_password => "postgres"
    statement => "select m.* FROM members m WHERE m.id > :sql_last_value ORDER BY m.id ASC"
    schedule => "*/2 * * * *"
    sql_log_level => "debug"
    tracking_column => "id"
    use_column_value => true
    record_last_run => true
    last_run_metadata_path => "/usr/share/logstash/member_last_run_metadata"
  }
}
filter {
  mutate {
    remove_field => ["@version", "jdbc_connection_string", "jdbc_user", "jdbc_password","password","provider_id","create_date","modify_date"]
  }
}
output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "members"
        document_id => "%{id}"
        manage_template => true
        template_name => "membertemplate"
        template => "/usr/share/logstash/template/MemberTemplate.json"
        template_overwrite => true
      }
}